# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: customers-service

# before:
#   hooks:
#     - make ci

builds:
  - id: customers-service
    main: ./cmd/app/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

gomod:
  proxy: true

checksum:
  name_template: "checksum.txt"

# source:
#   enabled: true
#
sboms:
  - artifacts: archive
  # - id: source
  #   artifacts: source

# signs:
#   - cmd: cosign
#     certificate: "${artifact}.pem"
#     args:
#       - sign-blob
#       - "--output-certificate=${certificate}"
#       - "--output-signature=${signature}"
#       - "${artifact}"
#       - "--yes" # needed on cosign 2.0.0+
#     artifacts: checksum
#     output: true

archives:
  - formats: [tar.gz]
    files:
      - ./configs/application.production.json
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers:
  - use: docker
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    skip_push: auto
    extra_files:
      - ./configs/application.json
      - ./configs/application.production.json

docker_signs:
  - cmd: cosign
    artifacts: images
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.REPO_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.REPO_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"

changelog:
  sort: "asc"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
