app:
  name: customers-detail-service
  logger: main

httpServers:
  host: 127.0.0.1
  instances:
    main:
      type: echo
      port: 8000
      debug: true
      logger: httpservermain

rpcServers:
  host: 0.0.0.0
  instances:
    main:
      type: grpc
      port: 9000
      debug: true
      logger: rpcservermain

loggers:
  type: logrus
  level: debug
  instances:
    main:
      prefix: customers-detail-service
    httpservermain:
      prefix: http-server (main)
    rpcservermain:
      prefix: rpc-server (main)

container:
  type: dig
